import 'dart:async';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';

const _channel = MethodChannel('com.wgorski.podcastr/youtube');
const _events = EventChannel('com.wgorski.podcastr/downloads');

/// What the Kotlin NewPipe Extractor bridge returns for a given YouTube URL.
/// Used only by the download sheet to render the resolve → ready preview.
/// The audio bytes are downloaded inside the foreground worker, which
/// re-resolves the URL itself at run time (googlevideo URLs expire).
class ResolvedVideo {
  final String videoId;
  final String title;
  final String channel;
  final int durationSeconds;
  final String audioUrl;
  final int averageBitrate;
  final String mimeType;
  final String extension;
  final String? thumbnailUrl;
  const ResolvedVideo({
    required this.videoId,
    required this.title,
    required this.channel,
    required this.durationSeconds,
    required this.audioUrl,
    required this.averageBitrate,
    required this.mimeType,
    required this.extension,
    required this.thumbnailUrl,
  });

  factory ResolvedVideo.fromMap(Map<dynamic, dynamic> m) => ResolvedVideo(
        videoId: m['videoId'] as String,
        title: m['title'] as String,
        channel: m['channel'] as String,
        durationSeconds: (m['durationSeconds'] as num).toInt(),
        audioUrl: m['audioUrl'] as String,
        averageBitrate: (m['averageBitrate'] as num).toInt(),
        mimeType: m['mimeType'] as String,
        extension: m['extension'] as String,
        thumbnailUrl: m['thumbnailUrl'] as String?,
      );

  String sizeLabelFromBytes(int bytes) => _formatSize(bytes);
}

class DownloadProgress {
  final int bytesReceived;
  final int totalBytes;
  const DownloadProgress(this.bytesReceived, this.totalBytes);
  double get fraction =>
      totalBytes <= 0 ? 0 : (bytesReceived / totalBytes).clamp(0.0, 1.0);
}

/// Strongly-typed download events streamed from the native EventChannel.
sealed class DownloadEvent {
  final String videoId;
  const DownloadEvent(this.videoId);
}

class DownloadQueued extends DownloadEvent {
  const DownloadQueued(super.videoId);
}

class DownloadProgressEvent extends DownloadEvent {
  final DownloadProgress progress;
  const DownloadProgressEvent(super.videoId, this.progress);
}

class DownloadCompleted extends DownloadEvent {
  final String filePath;
  final String? thumbnailPath;
  final String? subtitlePath;
  final String? subtitleLanguage;
  final bool subtitleAutoGenerated;
  final String title;
  final String channel;
  final int durationSeconds;
  final int bytesReceived;
  const DownloadCompleted({
    required String videoId,
    required this.filePath,
    required this.thumbnailPath,
    required this.subtitlePath,
    required this.subtitleLanguage,
    required this.subtitleAutoGenerated,
    required this.title,
    required this.channel,
    required this.durationSeconds,
    required this.bytesReceived,
  }) : super(videoId);
}

class DownloadFailed extends DownloadEvent {
  final String message;
  const DownloadFailed(super.videoId, this.message);
}

/// Façade over the Kotlin side: NewPipe extraction (`resolve`) + WorkManager
/// download lifecycle (`enqueue` / `cancel` / `abandon` / `restore`) + a
/// broadcast stream of progress / completion / failure events.
class YoutubeDownloader {
  Future<ResolvedVideo> resolve(String url) async {
    final result = await _channel.invokeMethod<Map<dynamic, dynamic>>(
      'resolve',
      {'url': url},
    );
    if (result == null) {
      throw const YoutubeException('Extractor returned no data.');
    }
    return ResolvedVideo.fromMap(result);
  }

  /// Schedule the actual byte download in the foreground worker. Returns as
  /// soon as the work is enqueued; progress / completion arrives via
  /// [events].
  Future<void> enqueue({
    required String videoId,
    required String sourceUrl,
    required String tracksDir,
    required String title,
    required String channel,
  }) async {
    await _channel.invokeMethod('enqueueDownload', {
      'videoId': videoId,
      'sourceUrl': sourceUrl,
      'tracksDir': tracksDir,
      'title': title,
      'channel': channel,
    });
  }

  /// Cancel an in-flight download. The worker observes [isStopped] and
  /// emits a [DownloadFailed] event with message "Cancelled" so the row
  /// remains in the library, marked as failed.
  Future<void> cancel(String videoId) =>
      _channel.invokeMethod('cancelDownload', {'videoId': videoId});

  /// Cancel the work AND stop observing it — used when the user deletes
  /// the row outright. No event is emitted.
  Future<void> abandon(String videoId) =>
      _channel.invokeMethod('abandonDownload', {'videoId': videoId});

  /// Re-attach to an existing piece of work after a process restart. The
  /// native side emits the current state on [events] synchronously
  /// (including [DownloadFailed] for pruned / missing work) and then
  /// continues to forward updates if the work is still running.
  Future<void> restore(String videoId) =>
      _channel.invokeMethod('restoreDownload', {'videoId': videoId});

  /// Broadcast stream — multiple subscribers see every event. Wrapped in a
  /// late getter so we don't create the underlying channel listener until
  /// the first subscriber.
  Stream<DownloadEvent> get events => _eventsStream;

  static final Stream<DownloadEvent> _eventsStream =
      _events.receiveBroadcastStream().map<DownloadEvent>(_decode);

  static DownloadEvent _decode(dynamic raw) {
    final m = (raw as Map).cast<dynamic, dynamic>();
    final type = m['type'] as String;
    final videoId = m['videoId'] as String;
    switch (type) {
      case 'queued':
        return DownloadQueued(videoId);
      case 'progress':
        return DownloadProgressEvent(
          videoId,
          DownloadProgress(
            (m['bytesReceived'] as num).toInt(),
            (m['totalBytes'] as num).toInt(),
          ),
        );
      case 'completed':
        return DownloadCompleted(
          videoId: videoId,
          filePath: m['filePath'] as String,
          thumbnailPath: m['thumbnailPath'] as String?,
          subtitlePath: m['subtitlePath'] as String?,
          subtitleLanguage: m['subtitleLanguage'] as String?,
          subtitleAutoGenerated: (m['subtitleAutoGenerated'] as bool?) ?? false,
          title: m['title'] as String? ?? '',
          channel: m['channel'] as String? ?? '',
          durationSeconds: (m['durationSeconds'] as num?)?.toInt() ?? 0,
          bytesReceived: (m['bytesReceived'] as num?)?.toInt() ?? 0,
        );
      case 'failed':
        return DownloadFailed(videoId, m['message'] as String? ?? 'Failed');
      default:
        return DownloadFailed(videoId, 'Unknown event: $type');
    }
  }

  /// Absolute path to the directory where tracks are written.
  static Future<String> tracksDir() async {
    final dir = await getApplicationDocumentsDirectory();
    final tracksDir = Directory('${dir.path}/tracks');
    if (!await tracksDir.exists()) {
      await tracksDir.create(recursive: true);
    }
    return tracksDir.path;
  }

  /// Predicted destination path (used before download starts, for the
  /// optimistic library row). The worker may pick a different extension
  /// after re-resolving — the canonical path is the one in the [DownloadCompleted]
  /// event.
  static Future<String> predictedFilePath(ResolvedVideo v) async {
    final dir = await tracksDir();
    return '$dir/${v.videoId}.${v.extension}';
  }
}

String _formatSize(int bytes) {
  if (bytes <= 0) return '— MB';
  final mb = bytes / (1024 * 1024);
  return '${mb.toStringAsFixed(1)} MB';
}

class YoutubeException implements Exception {
  final String message;
  const YoutubeException(this.message);
  @override
  String toString() => message;
}
